### PR TITLE
Feat/nonstandard proposals

### PR DESCRIPTION
**Pull request by miggol**
This adds the Attachments page to nonstandard proposals. It also somewhat changes the logic with which we construct non-standard proposals.

I have chosen to *not* define the preassessed/preapproved proposal flow in the "previous" checkers, i.e. where the next checker is returned. Now instead, we do the following:

```python3
def check(
        self,
    ):
        proposal = self.proposal
        if proposal.is_pre_assessment or proposal.is_pre_approved:
            return self.remaining_checkers()
```

So it's the trajectories checker that decides for itself that it is not needed for these proposals, and just continues. I think this is easier to keep track of. Wondering why WMO isn't showing up for preapproved proposals? Look in the `WMOChecker`, not the end of the Basic Details section.

DMP is also no longer recommended for preassessments and some intro text is added to the Attachments page.

### CODE REVIEW

**Review by EdoStorm96 — CHANGES_REQUESTED** [review]
That's a nice idea, to have each checker evaluate the proposal type! I like it. There is still some stuff not working with this PR though.

- We have specific views for submitting of PreApproved and PreAss ... So I guess we should use those for submitting the alt paths.
- Although the stepper is working, the forward and back buttons are not yet configured correctly.
- I noticed that ProposalSubmit does not redirect back to translations. This is an unrelated error, but could you fix it here as well?

**Comment by miggol** [comment]
Alright, I have addressed your comments.

I have also fixed that PreAssessments were not validated in ProposalSubmit. My blame diagnosis is that that specific if statement was there because of document validation, and the Embargo error checking was erroneously included inside of it after.

I will be addressing #663 in a separate PR.

**Comment by miggol** [comment]
Thank you again for being thorough. Some time could have been saved if I had done a full check myself, which I have now done. Found some more stuff I missed

**Review by EdoStorm96 — CHANGES_REQUESTED** [review]
Haha ok ... almost done here. The bug i outlined still persists. 

I should have explained it better. So if you start a new PreAss proposal, and you come to the first wmo page for the first time (/proposals/wmo/create/{pk}/pre/) and then you click the back button, you get an attribute error. Because WMOCreatePreAssessment, is trying to do PreAssesmentMixin.get_back_url(), but it doesn't have a self.object. All views inheriting from this method do have access to a get_proposal method, so just replace self.object.proposal with get_proposal() and we're good.

**Pull request merged**
