### PR TITLE
Fix/bugfix and textual changes

### LINKED ISSUE #634: "Details on the review process of application"
Could this phrase be deleted from the 'details' page? It is now confusing where the title of the application starts. If this phrase needs to be included on this page, perhaps better as a heading. However, I do not mind if it is deleted altogether.

### PR DESCRIPTION
**Pull request by EdoStorm96**
Fixes #634, #641 and #642. 

#642 and #643 are textual changes. #641 was a bug caused by an incorrect refactor, when changing the choices to model choices ... The labels for the two different options in `PracticeReasons` were switched around ... my bad ;p

### CODE REVIEW

**Comment by EdoStorm96** [comment]
I have also just included a fix for #624. This just adds `proposal.date_reviewed` to the "Continuation:" section of review_detail_sidebar.html.

**Review by tymees — APPROVED** [review]
I only looked at the diff in GH, so no real full review, as the changes are minor.

LGTM :)

(Sidenote, you forgot to tag #624 in your description, this PR fixes that one as well I think).

**Comment by EdoStorm96** [comment]
Decided to just push on more fix to this branch, as it was also a textual change. this fixes #608. Now I will leave this PR alone, haha. Could you have one more look, @tymees? :innocent:

**Comment by tymees** [comment]
Ehhh, I'm not great at reviewing these textual changes. I'm kinda word-blind remember?

The only check I would do is seeing if the translations apply correctly, but I trust you to have tested that ;)

If you really want me to make a comment, there's some junk gathering at the end of the `.po` file (due to outdated translations being moved there automatically). It's a pet-peeve of mine, but not a problem ;)

**Pull request merged**
