### PR TITLE
Feature/small issues

### PR DESCRIPTION
**Pull request by EdoStorm96**
This pull request fixes multiple small issues. Namely #499 and #454. So I've changed the cover image and change all occurences of UIL OTS to ILS. UIL OTS was featured in a fixture, which I've changed, but I've also changed this on the server through the admin site, following Michael's advice. Changing the fixture and running loaddata caused no errors on my local version of the code.

I also looked at issue #472, changing the names of UDS and DH Lab, but I've found no occurences of them, so this issue can also be closed IMHO.

### CODE REVIEW

**Review by miggol — CHANGES_REQUESTED** [review]
Small issue: The photo credit at the bottom of the frontpage no longer corresponds with the actual picture. Or at least so I think. It would be a huge coincidence if in fact it did.

Not that much of an issue: Considering I don't know the credit for the summer image anymore, maybe it would be an idea to grab a new one off of [the new beeldbank](https://intranet.uu.nl/nieuws/mededelingen/huisstijlplatform-gelanceerd-direct-avg-proof-fotos-downloaden)? 

But fixing the credit and keeping the old summer image is also fine to me.

**Comment by tymees** [comment]
We don't have a credit for that image; it's pulled from sites.uu.nl

**Comment by EdoStorm96** [comment]
Ok, I took a new cover image from the beeldbank, and credited the appropriate author. What do you think, @miggol ?

**Review by miggol — COMMENTED** [review]
Looks good to me! I like the picture, would work well for the fall as well.

**Review by miggol — APPROVED** [review]
Looks good to me! I like the picture, it would work well for later in the year as well.

**Pull request merged**
